project:
  type: website

website:
  title: "GLACIORAIDE"
  navbar:
    logo: "assets/logo-glacioraide.png"
    favicon: "assets/logo-glacioraide.png"
    left:
      - href: index.qmd
        text: Home
      - href: linceul.qmd
        text: Linceul
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
